import { fieldAtom, formAtom } from "form-atoms";
import type { NextPage } from "next";
import Head from "next/head";
import * as React from "react";
import { Fieldset } from "@/components/fieldset";
import { Form } from "@/components/form";
import { Input } from "@/components/input";
import { vstack } from "@/styles/layout";
import { valid, validate } from "@/utils/validate";
import { Select } from "@/components/select";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUpForm />
    </div>
  );
};

const signUpFormAtom = formAtom({
  email: fieldAtom({
    value: "",
    validate: validate.onChange(valid.email.required()),
  }),
  displayName: fieldAtom({
    value: "",
    validate: validate.onChange(valid.displayName.required()),
  }),
  password: fieldAtom({
    value: "",
    validate: validate.onChange(valid.password.required()),
  }),
});

function SignUpForm() {
  return (
    <Form
      atom={signUpFormAtom}
      className={vstack({ gap: 400 })}
      onSubmit={(values) => {
        console.log(values);
      }}
    >
      {(fieldAtoms) => (
        <Fieldset>
          <Fieldset.Legend>
            <span>Sign up</span>
          </Fieldset.Legend>

          <Form.Field atom={fieldAtoms.email}>
            <Input
              aria-label="Your email address"
              placeholder="example@theoretic.dev"
              autoComplete="email"
            />
          </Form.Field>

          <Form.Field atom={fieldAtoms.displayName}>
            <Input placeholder="Display name" autoComplete="username" />
          </Form.Field>

          <Form.Field atom={fieldAtoms.password}>
            <Input
              type="password"
              aria-label="Set a password"
              placeholder="********"
              autoComplete="new-password"
            />
          </Form.Field>
          <Select native>
            <Select.Option value=""></Select.Option>
            <Select.OptGroup label="Group">
              <Select.Option value="1">Hello</Select.Option>
            </Select.OptGroup>
          </Select>

          <button type="submit" hidden />
        </Fieldset>
      )}
    </Form>
  );
}

export default Home;
